[build]
  base = "web"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production Context (main branch)
[context.production.environment]
  VITE_API_URL = "https://agba-enterprise-api-dgefvzanqq-uc.a.run.app"

# Branch Deploys (dev branch)
[context.branch-deploy.environment]
  VITE_API_URL = "https://agba-enterprise-api-dev-dgefvzanqq-uc.a.run.app"

# Deploy Previews (Pull Requests)
[context.deploy-preview.environment]
  VITE_API_URL = "https://agba-enterprise-api-dev-dgefvzanqq-uc.a.run.app"
